// Roboto-Regular font for jsPDF (base64, generated by ttf2js)
// Download Roboto-Regular.ttf from Google Fonts, convert with https://rawgit.com/simonbengtsson/jsPDF-AutoTable/master/examples/fontconverter/fontconverter.html
// Example variable name: ROBOTO_BASE64
window.ROBOTO_BASE64 = ''; // (rút gọn, bạn cần dùng file đầy đủ)
